version: '3'

services:
  mariadb:
    env_file :
      - .env
    build:
      context : ./requirements/mariadb/.
      dockerfile: ./Dockerfile
    image: mariadb
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - backend

  wordpress:
    env_file :
      - .env
    build:
      context: ./requirements/wordpress/.
      dockerfile: ./Dockerfile
    depends_on:
      - mariadb
    image: wordpress
    container_name: wordpress
    restart: always
    volumes: 
      - wordpress:/var/www/wordpress
    networks:
      - backend
  
  nginx:
    build:
      context: ./requirements/nginx/.
      dockerfile: ./Dockerfile
    depends_on:
      - wordpress
    image: nginx
    container_name : nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress/
    restart: always
    networks:
      - backend

networks:
 backend:

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/shabibol/data/db_data
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type : none
      device: /home/shabibol/data/wordpress
      o: bind
