version: '3'
services:
  mariadb:
    env_file: .env
    build:
      context: ./requirements/mariadb/.
      dockerfile: ./Dockerfile
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always

  nginx:
    env_file: .env
    build:
      context: ./requirements/nginx/.
      dockerfile: ./Dockerfile
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    restart: always

  wordpress:
    env_file: .env
    build:
      context: ./requirements/wordpress/.
      dockerfile: ./Dockerfile
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    restart: always

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/shabibol/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      device: /home/shabibol/data/db_data
      o: 'bind'

networks:
  inception:
