version: '3'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    expose:
      - "3306"

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on: 
      - wordpress
    networks:
      - inception
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    restart: on_failure


  wordpress:
    image: wordpress:php7.3-fpm-alpine
    container_name: wordpress
    depends_on: 
      - mariadb
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    expose:
      - "9000"
    restart: on_failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/adrien/Desktop/InceptionShima/srcs/Data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
  
networks:
  inception:
    driver: bridge
